/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppWorkflowIndexRouteImport } from './routes/app.workflow.index'
import { Route as AppScreeningIndexRouteImport } from './routes/app.screening.index'
import { Route as AppRequisitionsIndexRouteImport } from './routes/app.requisitions.index'
import { Route as AppOffersIndexRouteImport } from './routes/app.offers.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app.notifications.index'
import { Route as AppInterviewsIndexRouteImport } from './routes/app.interviews.index'
import { Route as AppIdentityIndexRouteImport } from './routes/app.identity.index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app.documents.index'
import { Route as AppConfigIndexRouteImport } from './routes/app.config.index'
import { Route as AppCandidatesIndexRouteImport } from './routes/app.candidates.index'
import { Route as AppAuditIndexRouteImport } from './routes/app.audit.index'
import { Route as AppApplicationsIndexRouteImport } from './routes/app.applications.index'
import { Route as AppWorkflowInboxRouteImport } from './routes/app.workflow.inbox'
import { Route as AppWorkflowDefsRouteImport } from './routes/app.workflow.defs'
import { Route as AppScreeningScorecardsRouteImport } from './routes/app.screening.scorecards'
import { Route as AppRequisitionsNewRouteImport } from './routes/app.requisitions.new'
import { Route as AppRequisitionsIdRouteImport } from './routes/app.requisitions.$id'
import { Route as AppOffersNewRouteImport } from './routes/app.offers.new'
import { Route as AppOffersIdRouteImport } from './routes/app.offers.$id'
import { Route as AppNotificationsTemplatesRouteImport } from './routes/app.notifications.templates'
import { Route as AppNotificationsPreferencesRouteImport } from './routes/app.notifications.preferences'
import { Route as AppNotificationsLogRouteImport } from './routes/app.notifications.log'
import { Route as AppInterviewsIdRouteImport } from './routes/app.interviews.$id'
import { Route as AppConfigOrgRouteImport } from './routes/app.config.org'
import { Route as AppConfigLookupsRouteImport } from './routes/app.config.lookups'
import { Route as AppConfigJobsRouteImport } from './routes/app.config.jobs'
import { Route as AppConfigJdRouteImport } from './routes/app.config.jd'
import { Route as AppCandidatesIdRouteImport } from './routes/app.candidates.$id'
import { Route as AppApplicationsStagesRouteImport } from './routes/app.applications.stages'
import { Route as AppApplicationsBoardRouteImport } from './routes/app.applications.board'
import { Route as AppApplicationsIdRouteImport } from './routes/app.applications.$id'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app.admin.users.index'
import { Route as AppAdminUsersNewRouteImport } from './routes/app.admin.users.new'
import { Route as AppAdminUsersIdRouteImport } from './routes/app.admin.users.$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowIndexRoute = AppWorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => AppRoute,
} as any)
const AppScreeningIndexRoute = AppScreeningIndexRouteImport.update({
  id: '/screening/',
  path: '/screening/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsIndexRoute = AppRequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersIndexRoute = AppOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityIndexRoute = AppIdentityIndexRouteImport.update({
  id: '/identity/',
  path: '/identity/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowInboxRoute = AppWorkflowInboxRouteImport.update({
  id: '/workflow/inbox',
  path: '/workflow/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowDefsRoute = AppWorkflowDefsRouteImport.update({
  id: '/workflow/defs',
  path: '/workflow/defs',
  getParentRoute: () => AppRoute,
} as any)
const AppScreeningScorecardsRoute = AppScreeningScorecardsRouteImport.update({
  id: '/screening/scorecards',
  path: '/screening/scorecards',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsNewRoute = AppRequisitionsNewRouteImport.update({
  id: '/requisitions/new',
  path: '/requisitions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsIdRoute = AppRequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersNewRoute = AppOffersNewRouteImport.update({
  id: '/offers/new',
  path: '/offers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersIdRoute = AppOffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsTemplatesRoute =
  AppNotificationsTemplatesRouteImport.update({
    id: '/notifications/templates',
    path: '/notifications/templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppNotificationsPreferencesRoute =
  AppNotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AppRoute,
  } as any)
const AppNotificationsLogRoute = AppNotificationsLogRouteImport.update({
  id: '/notifications/log',
  path: '/notifications/log',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsIdRoute = AppInterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigOrgRoute = AppConfigOrgRouteImport.update({
  id: '/config/org',
  path: '/config/org',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigLookupsRoute = AppConfigLookupsRouteImport.update({
  id: '/config/lookups',
  path: '/config/lookups',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigJobsRoute = AppConfigJobsRouteImport.update({
  id: '/config/jobs',
  path: '/config/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigJdRoute = AppConfigJdRouteImport.update({
  id: '/config/jd',
  path: '/config/jd',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsStagesRoute = AppApplicationsStagesRouteImport.update({
  id: '/applications/stages',
  path: '/applications/stages',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsBoardRoute = AppApplicationsBoardRouteImport.update({
  id: '/applications/board',
  path: '/applications/board',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersNewRoute = AppAdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIdRoute = AppAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/signin': typeof SigninRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/board': typeof AppApplicationsBoardRoute
  '/app/applications/stages': typeof AppApplicationsStagesRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/interviews/$id': typeof AppInterviewsIdRoute
  '/app/notifications/log': typeof AppNotificationsLogRoute
  '/app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/app/notifications/templates': typeof AppNotificationsTemplatesRoute
  '/app/offers/$id': typeof AppOffersIdRoute
  '/app/offers/new': typeof AppOffersNewRoute
  '/app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/app/requisitions/new': typeof AppRequisitionsNewRoute
  '/app/screening/scorecards': typeof AppScreeningScorecardsRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
  '/app/audit/': typeof AppAuditIndexRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/offers/': typeof AppOffersIndexRoute
  '/app/requisitions/': typeof AppRequisitionsIndexRoute
  '/app/screening/': typeof AppScreeningIndexRoute
  '/app/workflow/': typeof AppWorkflowIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/new': typeof AppAdminUsersNewRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/signin': typeof SigninRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/board': typeof AppApplicationsBoardRoute
  '/app/applications/stages': typeof AppApplicationsStagesRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/interviews/$id': typeof AppInterviewsIdRoute
  '/app/notifications/log': typeof AppNotificationsLogRoute
  '/app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/app/notifications/templates': typeof AppNotificationsTemplatesRoute
  '/app/offers/$id': typeof AppOffersIdRoute
  '/app/offers/new': typeof AppOffersNewRoute
  '/app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/app/requisitions/new': typeof AppRequisitionsNewRoute
  '/app/screening/scorecards': typeof AppScreeningScorecardsRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/applications': typeof AppApplicationsIndexRoute
  '/app/audit': typeof AppAuditIndexRoute
  '/app/candidates': typeof AppCandidatesIndexRoute
  '/app/config': typeof AppConfigIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/identity': typeof AppIdentityIndexRoute
  '/app/interviews': typeof AppInterviewsIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/offers': typeof AppOffersIndexRoute
  '/app/requisitions': typeof AppRequisitionsIndexRoute
  '/app/screening': typeof AppScreeningIndexRoute
  '/app/workflow': typeof AppWorkflowIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/new': typeof AppAdminUsersNewRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/signin': typeof SigninRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/board': typeof AppApplicationsBoardRoute
  '/app/applications/stages': typeof AppApplicationsStagesRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/interviews/$id': typeof AppInterviewsIdRoute
  '/app/notifications/log': typeof AppNotificationsLogRoute
  '/app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/app/notifications/templates': typeof AppNotificationsTemplatesRoute
  '/app/offers/$id': typeof AppOffersIdRoute
  '/app/offers/new': typeof AppOffersNewRoute
  '/app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/app/requisitions/new': typeof AppRequisitionsNewRoute
  '/app/screening/scorecards': typeof AppScreeningScorecardsRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
  '/app/audit/': typeof AppAuditIndexRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/offers/': typeof AppOffersIndexRoute
  '/app/requisitions/': typeof AppRequisitionsIndexRoute
  '/app/screening/': typeof AppScreeningIndexRoute
  '/app/workflow/': typeof AppWorkflowIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/new': typeof AppAdminUsersNewRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/no-access'
    | '/signin'
    | '/auth/callback'
    | '/app/'
    | '/app/applications/$id'
    | '/app/applications/board'
    | '/app/applications/stages'
    | '/app/candidates/$id'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/interviews/$id'
    | '/app/notifications/log'
    | '/app/notifications/preferences'
    | '/app/notifications/templates'
    | '/app/offers/$id'
    | '/app/offers/new'
    | '/app/requisitions/$id'
    | '/app/requisitions/new'
    | '/app/screening/scorecards'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/applications/'
    | '/app/audit/'
    | '/app/candidates/'
    | '/app/config/'
    | '/app/documents/'
    | '/app/identity/'
    | '/app/interviews/'
    | '/app/notifications/'
    | '/app/offers/'
    | '/app/requisitions/'
    | '/app/screening/'
    | '/app/workflow/'
    | '/app/admin/users/$id'
    | '/app/admin/users/new'
    | '/app/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/signin'
    | '/auth/callback'
    | '/app'
    | '/app/applications/$id'
    | '/app/applications/board'
    | '/app/applications/stages'
    | '/app/candidates/$id'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/interviews/$id'
    | '/app/notifications/log'
    | '/app/notifications/preferences'
    | '/app/notifications/templates'
    | '/app/offers/$id'
    | '/app/offers/new'
    | '/app/requisitions/$id'
    | '/app/requisitions/new'
    | '/app/screening/scorecards'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/applications'
    | '/app/audit'
    | '/app/candidates'
    | '/app/config'
    | '/app/documents'
    | '/app/identity'
    | '/app/interviews'
    | '/app/notifications'
    | '/app/offers'
    | '/app/requisitions'
    | '/app/screening'
    | '/app/workflow'
    | '/app/admin/users/$id'
    | '/app/admin/users/new'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/no-access'
    | '/signin'
    | '/auth/callback'
    | '/app/'
    | '/app/applications/$id'
    | '/app/applications/board'
    | '/app/applications/stages'
    | '/app/candidates/$id'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/interviews/$id'
    | '/app/notifications/log'
    | '/app/notifications/preferences'
    | '/app/notifications/templates'
    | '/app/offers/$id'
    | '/app/offers/new'
    | '/app/requisitions/$id'
    | '/app/requisitions/new'
    | '/app/screening/scorecards'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/applications/'
    | '/app/audit/'
    | '/app/candidates/'
    | '/app/config/'
    | '/app/documents/'
    | '/app/identity/'
    | '/app/interviews/'
    | '/app/notifications/'
    | '/app/offers/'
    | '/app/requisitions/'
    | '/app/screening/'
    | '/app/workflow/'
    | '/app/admin/users/$id'
    | '/app/admin/users/new'
    | '/app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  SigninRoute: typeof SigninRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflow/': {
      id: '/app/workflow/'
      path: '/workflow'
      fullPath: '/app/workflow/'
      preLoaderRoute: typeof AppWorkflowIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/screening/': {
      id: '/app/screening/'
      path: '/screening'
      fullPath: '/app/screening/'
      preLoaderRoute: typeof AppScreeningIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requisitions/': {
      id: '/app/requisitions/'
      path: '/requisitions'
      fullPath: '/app/requisitions/'
      preLoaderRoute: typeof AppRequisitionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offers/': {
      id: '/app/offers/'
      path: '/offers'
      fullPath: '/app/offers/'
      preLoaderRoute: typeof AppOffersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews/': {
      id: '/app/interviews/'
      path: '/interviews'
      fullPath: '/app/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity/': {
      id: '/app/identity/'
      path: '/identity'
      fullPath: '/app/identity/'
      preLoaderRoute: typeof AppIdentityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/': {
      id: '/app/config/'
      path: '/config'
      fullPath: '/app/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/': {
      id: '/app/candidates/'
      path: '/candidates'
      fullPath: '/app/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit/': {
      id: '/app/audit/'
      path: '/audit'
      fullPath: '/app/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/': {
      id: '/app/applications/'
      path: '/applications'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/inbox': {
      id: '/app/workflow/inbox'
      path: '/workflow/inbox'
      fullPath: '/app/workflow/inbox'
      preLoaderRoute: typeof AppWorkflowInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/defs': {
      id: '/app/workflow/defs'
      path: '/workflow/defs'
      fullPath: '/app/workflow/defs'
      preLoaderRoute: typeof AppWorkflowDefsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/screening/scorecards': {
      id: '/app/screening/scorecards'
      path: '/screening/scorecards'
      fullPath: '/app/screening/scorecards'
      preLoaderRoute: typeof AppScreeningScorecardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requisitions/new': {
      id: '/app/requisitions/new'
      path: '/requisitions/new'
      fullPath: '/app/requisitions/new'
      preLoaderRoute: typeof AppRequisitionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requisitions/$id': {
      id: '/app/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/app/requisitions/$id'
      preLoaderRoute: typeof AppRequisitionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offers/new': {
      id: '/app/offers/new'
      path: '/offers/new'
      fullPath: '/app/offers/new'
      preLoaderRoute: typeof AppOffersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offers/$id': {
      id: '/app/offers/$id'
      path: '/offers/$id'
      fullPath: '/app/offers/$id'
      preLoaderRoute: typeof AppOffersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/templates': {
      id: '/app/notifications/templates'
      path: '/notifications/templates'
      fullPath: '/app/notifications/templates'
      preLoaderRoute: typeof AppNotificationsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/preferences': {
      id: '/app/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/app/notifications/preferences'
      preLoaderRoute: typeof AppNotificationsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/log': {
      id: '/app/notifications/log'
      path: '/notifications/log'
      fullPath: '/app/notifications/log'
      preLoaderRoute: typeof AppNotificationsLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews/$id': {
      id: '/app/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/app/interviews/$id'
      preLoaderRoute: typeof AppInterviewsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/org': {
      id: '/app/config/org'
      path: '/config/org'
      fullPath: '/app/config/org'
      preLoaderRoute: typeof AppConfigOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/lookups': {
      id: '/app/config/lookups'
      path: '/config/lookups'
      fullPath: '/app/config/lookups'
      preLoaderRoute: typeof AppConfigLookupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/jobs': {
      id: '/app/config/jobs'
      path: '/config/jobs'
      fullPath: '/app/config/jobs'
      preLoaderRoute: typeof AppConfigJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/jd': {
      id: '/app/config/jd'
      path: '/config/jd'
      fullPath: '/app/config/jd'
      preLoaderRoute: typeof AppConfigJdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/$id': {
      id: '/app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/app/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/stages': {
      id: '/app/applications/stages'
      path: '/applications/stages'
      fullPath: '/app/applications/stages'
      preLoaderRoute: typeof AppApplicationsStagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/board': {
      id: '/app/applications/board'
      path: '/applications/board'
      fullPath: '/app/applications/board'
      preLoaderRoute: typeof AppApplicationsBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/$id': {
      id: '/app/applications/$id'
      path: '/applications/$id'
      fullPath: '/app/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/admin/users'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users/new': {
      id: '/app/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/app/admin/users/new'
      preLoaderRoute: typeof AppAdminUsersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users/$id': {
      id: '/app/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/app/admin/users/$id'
      preLoaderRoute: typeof AppAdminUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppApplicationsBoardRoute: typeof AppApplicationsBoardRoute
  AppApplicationsStagesRoute: typeof AppApplicationsStagesRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppConfigJdRoute: typeof AppConfigJdRoute
  AppConfigJobsRoute: typeof AppConfigJobsRoute
  AppConfigLookupsRoute: typeof AppConfigLookupsRoute
  AppConfigOrgRoute: typeof AppConfigOrgRoute
  AppInterviewsIdRoute: typeof AppInterviewsIdRoute
  AppNotificationsLogRoute: typeof AppNotificationsLogRoute
  AppNotificationsPreferencesRoute: typeof AppNotificationsPreferencesRoute
  AppNotificationsTemplatesRoute: typeof AppNotificationsTemplatesRoute
  AppOffersIdRoute: typeof AppOffersIdRoute
  AppOffersNewRoute: typeof AppOffersNewRoute
  AppRequisitionsIdRoute: typeof AppRequisitionsIdRoute
  AppRequisitionsNewRoute: typeof AppRequisitionsNewRoute
  AppScreeningScorecardsRoute: typeof AppScreeningScorecardsRoute
  AppWorkflowDefsRoute: typeof AppWorkflowDefsRoute
  AppWorkflowInboxRoute: typeof AppWorkflowInboxRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppIdentityIndexRoute: typeof AppIdentityIndexRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppOffersIndexRoute: typeof AppOffersIndexRoute
  AppRequisitionsIndexRoute: typeof AppRequisitionsIndexRoute
  AppScreeningIndexRoute: typeof AppScreeningIndexRoute
  AppWorkflowIndexRoute: typeof AppWorkflowIndexRoute
  AppAdminUsersIdRoute: typeof AppAdminUsersIdRoute
  AppAdminUsersNewRoute: typeof AppAdminUsersNewRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppApplicationsBoardRoute: AppApplicationsBoardRoute,
  AppApplicationsStagesRoute: AppApplicationsStagesRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppConfigJdRoute: AppConfigJdRoute,
  AppConfigJobsRoute: AppConfigJobsRoute,
  AppConfigLookupsRoute: AppConfigLookupsRoute,
  AppConfigOrgRoute: AppConfigOrgRoute,
  AppInterviewsIdRoute: AppInterviewsIdRoute,
  AppNotificationsLogRoute: AppNotificationsLogRoute,
  AppNotificationsPreferencesRoute: AppNotificationsPreferencesRoute,
  AppNotificationsTemplatesRoute: AppNotificationsTemplatesRoute,
  AppOffersIdRoute: AppOffersIdRoute,
  AppOffersNewRoute: AppOffersNewRoute,
  AppRequisitionsIdRoute: AppRequisitionsIdRoute,
  AppRequisitionsNewRoute: AppRequisitionsNewRoute,
  AppScreeningScorecardsRoute: AppScreeningScorecardsRoute,
  AppWorkflowDefsRoute: AppWorkflowDefsRoute,
  AppWorkflowInboxRoute: AppWorkflowInboxRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppIdentityIndexRoute: AppIdentityIndexRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppOffersIndexRoute: AppOffersIndexRoute,
  AppRequisitionsIndexRoute: AppRequisitionsIndexRoute,
  AppScreeningIndexRoute: AppScreeningIndexRoute,
  AppWorkflowIndexRoute: AppWorkflowIndexRoute,
  AppAdminUsersIdRoute: AppAdminUsersIdRoute,
  AppAdminUsersNewRoute: AppAdminUsersNewRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  SigninRoute: SigninRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
