/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkflowIndexRouteImport } from './routes/app.workflow.index'
import { Route as AppRequisitionsIndexRouteImport } from './routes/app.requisitions.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app.notifications.index'
import { Route as AppIdentityIndexRouteImport } from './routes/app.identity.index'
import { Route as AppDocumentsIndexRouteImport } from './routes/app.documents.index'
import { Route as AppConfigIndexRouteImport } from './routes/app.config.index'
import { Route as AppCandidatesIndexRouteImport } from './routes/app.candidates.index'
import { Route as AppAuditIndexRouteImport } from './routes/app.audit.index'
import { Route as AppApplicationsIndexRouteImport } from './routes/app.applications.index'
import { Route as AppWorkflowInboxRouteImport } from './routes/app.workflow.inbox'
import { Route as AppWorkflowDefsRouteImport } from './routes/app.workflow.defs'
import { Route as AppRequisitionsNewRouteImport } from './routes/app.requisitions.new'
import { Route as AppRequisitionsIdRouteImport } from './routes/app.requisitions.$id'
import { Route as AppNotificationsTemplatesRouteImport } from './routes/app.notifications.templates'
import { Route as AppNotificationsPreferencesRouteImport } from './routes/app.notifications.preferences'
import { Route as AppNotificationsLogRouteImport } from './routes/app.notifications.log'
import { Route as AppConfigOrgRouteImport } from './routes/app.config.org'
import { Route as AppConfigLookupsRouteImport } from './routes/app.config.lookups'
import { Route as AppConfigJobsRouteImport } from './routes/app.config.jobs'
import { Route as AppConfigJdRouteImport } from './routes/app.config.jd'
import { Route as AppCandidatesIdRouteImport } from './routes/app.candidates.$id'
import { Route as AppApplicationsStagesRouteImport } from './routes/app.applications.stages'
import { Route as AppApplicationsBoardRouteImport } from './routes/app.applications.board'
import { Route as AppApplicationsIdRouteImport } from './routes/app.applications.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowIndexRoute = AppWorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsIndexRoute = AppRequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityIndexRoute = AppIdentityIndexRouteImport.update({
  id: '/identity/',
  path: '/identity/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowInboxRoute = AppWorkflowInboxRouteImport.update({
  id: '/workflow/inbox',
  path: '/workflow/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowDefsRoute = AppWorkflowDefsRouteImport.update({
  id: '/workflow/defs',
  path: '/workflow/defs',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsNewRoute = AppRequisitionsNewRouteImport.update({
  id: '/requisitions/new',
  path: '/requisitions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsIdRoute = AppRequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsTemplatesRoute =
  AppNotificationsTemplatesRouteImport.update({
    id: '/notifications/templates',
    path: '/notifications/templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppNotificationsPreferencesRoute =
  AppNotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AppRoute,
  } as any)
const AppNotificationsLogRoute = AppNotificationsLogRouteImport.update({
  id: '/notifications/log',
  path: '/notifications/log',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigOrgRoute = AppConfigOrgRouteImport.update({
  id: '/config/org',
  path: '/config/org',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigLookupsRoute = AppConfigLookupsRouteImport.update({
  id: '/config/lookups',
  path: '/config/lookups',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigJobsRoute = AppConfigJobsRouteImport.update({
  id: '/config/jobs',
  path: '/config/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigJdRoute = AppConfigJdRouteImport.update({
  id: '/config/jd',
  path: '/config/jd',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsStagesRoute = AppApplicationsStagesRouteImport.update({
  id: '/applications/stages',
  path: '/applications/stages',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsBoardRoute = AppApplicationsBoardRouteImport.update({
  id: '/applications/board',
  path: '/applications/board',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/board': typeof AppApplicationsBoardRoute
  '/app/applications/stages': typeof AppApplicationsStagesRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/notifications/log': typeof AppNotificationsLogRoute
  '/app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/app/notifications/templates': typeof AppNotificationsTemplatesRoute
  '/app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/app/requisitions/new': typeof AppRequisitionsNewRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
  '/app/audit/': typeof AppAuditIndexRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/requisitions/': typeof AppRequisitionsIndexRoute
  '/app/workflow/': typeof AppWorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/board': typeof AppApplicationsBoardRoute
  '/app/applications/stages': typeof AppApplicationsStagesRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/notifications/log': typeof AppNotificationsLogRoute
  '/app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/app/notifications/templates': typeof AppNotificationsTemplatesRoute
  '/app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/app/requisitions/new': typeof AppRequisitionsNewRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/applications': typeof AppApplicationsIndexRoute
  '/app/audit': typeof AppAuditIndexRoute
  '/app/candidates': typeof AppCandidatesIndexRoute
  '/app/config': typeof AppConfigIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/identity': typeof AppIdentityIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/requisitions': typeof AppRequisitionsIndexRoute
  '/app/workflow': typeof AppWorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/applications/$id': typeof AppApplicationsIdRoute
  '/app/applications/board': typeof AppApplicationsBoardRoute
  '/app/applications/stages': typeof AppApplicationsStagesRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/notifications/log': typeof AppNotificationsLogRoute
  '/app/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/app/notifications/templates': typeof AppNotificationsTemplatesRoute
  '/app/requisitions/$id': typeof AppRequisitionsIdRoute
  '/app/requisitions/new': typeof AppRequisitionsNewRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
  '/app/audit/': typeof AppAuditIndexRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/requisitions/': typeof AppRequisitionsIndexRoute
  '/app/workflow/': typeof AppWorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/applications/$id'
    | '/app/applications/board'
    | '/app/applications/stages'
    | '/app/candidates/$id'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/notifications/log'
    | '/app/notifications/preferences'
    | '/app/notifications/templates'
    | '/app/requisitions/$id'
    | '/app/requisitions/new'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/applications/'
    | '/app/audit/'
    | '/app/candidates/'
    | '/app/config/'
    | '/app/documents/'
    | '/app/identity/'
    | '/app/notifications/'
    | '/app/requisitions/'
    | '/app/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/applications/$id'
    | '/app/applications/board'
    | '/app/applications/stages'
    | '/app/candidates/$id'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/notifications/log'
    | '/app/notifications/preferences'
    | '/app/notifications/templates'
    | '/app/requisitions/$id'
    | '/app/requisitions/new'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/applications'
    | '/app/audit'
    | '/app/candidates'
    | '/app/config'
    | '/app/documents'
    | '/app/identity'
    | '/app/notifications'
    | '/app/requisitions'
    | '/app/workflow'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/applications/$id'
    | '/app/applications/board'
    | '/app/applications/stages'
    | '/app/candidates/$id'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/notifications/log'
    | '/app/notifications/preferences'
    | '/app/notifications/templates'
    | '/app/requisitions/$id'
    | '/app/requisitions/new'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/applications/'
    | '/app/audit/'
    | '/app/candidates/'
    | '/app/config/'
    | '/app/documents/'
    | '/app/identity/'
    | '/app/notifications/'
    | '/app/requisitions/'
    | '/app/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/': {
      id: '/app/workflow/'
      path: '/workflow'
      fullPath: '/app/workflow/'
      preLoaderRoute: typeof AppWorkflowIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requisitions/': {
      id: '/app/requisitions/'
      path: '/requisitions'
      fullPath: '/app/requisitions/'
      preLoaderRoute: typeof AppRequisitionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity/': {
      id: '/app/identity/'
      path: '/identity'
      fullPath: '/app/identity/'
      preLoaderRoute: typeof AppIdentityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/': {
      id: '/app/config/'
      path: '/config'
      fullPath: '/app/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/': {
      id: '/app/candidates/'
      path: '/candidates'
      fullPath: '/app/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit/': {
      id: '/app/audit/'
      path: '/audit'
      fullPath: '/app/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/': {
      id: '/app/applications/'
      path: '/applications'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/inbox': {
      id: '/app/workflow/inbox'
      path: '/workflow/inbox'
      fullPath: '/app/workflow/inbox'
      preLoaderRoute: typeof AppWorkflowInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/defs': {
      id: '/app/workflow/defs'
      path: '/workflow/defs'
      fullPath: '/app/workflow/defs'
      preLoaderRoute: typeof AppWorkflowDefsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requisitions/new': {
      id: '/app/requisitions/new'
      path: '/requisitions/new'
      fullPath: '/app/requisitions/new'
      preLoaderRoute: typeof AppRequisitionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requisitions/$id': {
      id: '/app/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/app/requisitions/$id'
      preLoaderRoute: typeof AppRequisitionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/templates': {
      id: '/app/notifications/templates'
      path: '/notifications/templates'
      fullPath: '/app/notifications/templates'
      preLoaderRoute: typeof AppNotificationsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/preferences': {
      id: '/app/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/app/notifications/preferences'
      preLoaderRoute: typeof AppNotificationsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications/log': {
      id: '/app/notifications/log'
      path: '/notifications/log'
      fullPath: '/app/notifications/log'
      preLoaderRoute: typeof AppNotificationsLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/org': {
      id: '/app/config/org'
      path: '/config/org'
      fullPath: '/app/config/org'
      preLoaderRoute: typeof AppConfigOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/lookups': {
      id: '/app/config/lookups'
      path: '/config/lookups'
      fullPath: '/app/config/lookups'
      preLoaderRoute: typeof AppConfigLookupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/jobs': {
      id: '/app/config/jobs'
      path: '/config/jobs'
      fullPath: '/app/config/jobs'
      preLoaderRoute: typeof AppConfigJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/jd': {
      id: '/app/config/jd'
      path: '/config/jd'
      fullPath: '/app/config/jd'
      preLoaderRoute: typeof AppConfigJdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/$id': {
      id: '/app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/app/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/stages': {
      id: '/app/applications/stages'
      path: '/applications/stages'
      fullPath: '/app/applications/stages'
      preLoaderRoute: typeof AppApplicationsStagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/board': {
      id: '/app/applications/board'
      path: '/applications/board'
      fullPath: '/app/applications/board'
      preLoaderRoute: typeof AppApplicationsBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/$id': {
      id: '/app/applications/$id'
      path: '/applications/$id'
      fullPath: '/app/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppApplicationsBoardRoute: typeof AppApplicationsBoardRoute
  AppApplicationsStagesRoute: typeof AppApplicationsStagesRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppConfigJdRoute: typeof AppConfigJdRoute
  AppConfigJobsRoute: typeof AppConfigJobsRoute
  AppConfigLookupsRoute: typeof AppConfigLookupsRoute
  AppConfigOrgRoute: typeof AppConfigOrgRoute
  AppNotificationsLogRoute: typeof AppNotificationsLogRoute
  AppNotificationsPreferencesRoute: typeof AppNotificationsPreferencesRoute
  AppNotificationsTemplatesRoute: typeof AppNotificationsTemplatesRoute
  AppRequisitionsIdRoute: typeof AppRequisitionsIdRoute
  AppRequisitionsNewRoute: typeof AppRequisitionsNewRoute
  AppWorkflowDefsRoute: typeof AppWorkflowDefsRoute
  AppWorkflowInboxRoute: typeof AppWorkflowInboxRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppIdentityIndexRoute: typeof AppIdentityIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppRequisitionsIndexRoute: typeof AppRequisitionsIndexRoute
  AppWorkflowIndexRoute: typeof AppWorkflowIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppApplicationsBoardRoute: AppApplicationsBoardRoute,
  AppApplicationsStagesRoute: AppApplicationsStagesRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppConfigJdRoute: AppConfigJdRoute,
  AppConfigJobsRoute: AppConfigJobsRoute,
  AppConfigLookupsRoute: AppConfigLookupsRoute,
  AppConfigOrgRoute: AppConfigOrgRoute,
  AppNotificationsLogRoute: AppNotificationsLogRoute,
  AppNotificationsPreferencesRoute: AppNotificationsPreferencesRoute,
  AppNotificationsTemplatesRoute: AppNotificationsTemplatesRoute,
  AppRequisitionsIdRoute: AppRequisitionsIdRoute,
  AppRequisitionsNewRoute: AppRequisitionsNewRoute,
  AppWorkflowDefsRoute: AppWorkflowDefsRoute,
  AppWorkflowInboxRoute: AppWorkflowInboxRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppIdentityIndexRoute: AppIdentityIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppRequisitionsIndexRoute: AppRequisitionsIndexRoute,
  AppWorkflowIndexRoute: AppWorkflowIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
