/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkflowIndexRouteImport } from './routes/app.workflow.index'
import { Route as AppIdentityIndexRouteImport } from './routes/app.identity.index'
import { Route as AppConfigIndexRouteImport } from './routes/app.config.index'
import { Route as AppWorkflowInboxRouteImport } from './routes/app.workflow.inbox'
import { Route as AppWorkflowDefsRouteImport } from './routes/app.workflow.defs'
import { Route as AppConfigOrgRouteImport } from './routes/app.config.org'
import { Route as AppConfigLookupsRouteImport } from './routes/app.config.lookups'
import { Route as AppConfigJobsRouteImport } from './routes/app.config.jobs'
import { Route as AppConfigJdRouteImport } from './routes/app.config.jd'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowIndexRoute = AppWorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityIndexRoute = AppIdentityIndexRouteImport.update({
  id: '/identity/',
  path: '/identity/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowInboxRoute = AppWorkflowInboxRouteImport.update({
  id: '/workflow/inbox',
  path: '/workflow/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowDefsRoute = AppWorkflowDefsRouteImport.update({
  id: '/workflow/defs',
  path: '/workflow/defs',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigOrgRoute = AppConfigOrgRouteImport.update({
  id: '/config/org',
  path: '/config/org',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigLookupsRoute = AppConfigLookupsRouteImport.update({
  id: '/config/lookups',
  path: '/config/lookups',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigJobsRoute = AppConfigJobsRouteImport.update({
  id: '/config/jobs',
  path: '/config/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigJdRoute = AppConfigJdRouteImport.update({
  id: '/config/jd',
  path: '/config/jd',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/workflow/': typeof AppWorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/config': typeof AppConfigIndexRoute
  '/app/identity': typeof AppIdentityIndexRoute
  '/app/workflow': typeof AppWorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/config/jd': typeof AppConfigJdRoute
  '/app/config/jobs': typeof AppConfigJobsRoute
  '/app/config/lookups': typeof AppConfigLookupsRoute
  '/app/config/org': typeof AppConfigOrgRoute
  '/app/workflow/defs': typeof AppWorkflowDefsRoute
  '/app/workflow/inbox': typeof AppWorkflowInboxRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/workflow/': typeof AppWorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/config/'
    | '/app/identity/'
    | '/app/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/config'
    | '/app/identity'
    | '/app/workflow'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/config/jd'
    | '/app/config/jobs'
    | '/app/config/lookups'
    | '/app/config/org'
    | '/app/workflow/defs'
    | '/app/workflow/inbox'
    | '/app/config/'
    | '/app/identity/'
    | '/app/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/': {
      id: '/app/workflow/'
      path: '/workflow'
      fullPath: '/app/workflow/'
      preLoaderRoute: typeof AppWorkflowIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity/': {
      id: '/app/identity/'
      path: '/identity'
      fullPath: '/app/identity/'
      preLoaderRoute: typeof AppIdentityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/': {
      id: '/app/config/'
      path: '/config'
      fullPath: '/app/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/inbox': {
      id: '/app/workflow/inbox'
      path: '/workflow/inbox'
      fullPath: '/app/workflow/inbox'
      preLoaderRoute: typeof AppWorkflowInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow/defs': {
      id: '/app/workflow/defs'
      path: '/workflow/defs'
      fullPath: '/app/workflow/defs'
      preLoaderRoute: typeof AppWorkflowDefsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/org': {
      id: '/app/config/org'
      path: '/config/org'
      fullPath: '/app/config/org'
      preLoaderRoute: typeof AppConfigOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/lookups': {
      id: '/app/config/lookups'
      path: '/config/lookups'
      fullPath: '/app/config/lookups'
      preLoaderRoute: typeof AppConfigLookupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/jobs': {
      id: '/app/config/jobs'
      path: '/config/jobs'
      fullPath: '/app/config/jobs'
      preLoaderRoute: typeof AppConfigJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config/jd': {
      id: '/app/config/jd'
      path: '/config/jd'
      fullPath: '/app/config/jd'
      preLoaderRoute: typeof AppConfigJdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppConfigJdRoute: typeof AppConfigJdRoute
  AppConfigJobsRoute: typeof AppConfigJobsRoute
  AppConfigLookupsRoute: typeof AppConfigLookupsRoute
  AppConfigOrgRoute: typeof AppConfigOrgRoute
  AppWorkflowDefsRoute: typeof AppWorkflowDefsRoute
  AppWorkflowInboxRoute: typeof AppWorkflowInboxRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
  AppIdentityIndexRoute: typeof AppIdentityIndexRoute
  AppWorkflowIndexRoute: typeof AppWorkflowIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppConfigJdRoute: AppConfigJdRoute,
  AppConfigJobsRoute: AppConfigJobsRoute,
  AppConfigLookupsRoute: AppConfigLookupsRoute,
  AppConfigOrgRoute: AppConfigOrgRoute,
  AppWorkflowDefsRoute: AppWorkflowDefsRoute,
  AppWorkflowInboxRoute: AppWorkflowInboxRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
  AppIdentityIndexRoute: AppIdentityIndexRoute,
  AppWorkflowIndexRoute: AppWorkflowIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
